FROM node:18-alpine AS build

ADD app/ /src/app/
ADD .npmrc /src/.npmrc
ADD package.json /src/package.json
ADD package-lock.json /src/package-lock.json
ADD svelte.config.js /src/svelte.config.js
ADD tsconfig.json /src/tsconfig.json
ADD vite.config.ts /src/vite.config.ts

WORKDIR /src

RUN npm ci && \
    npm run build

FROM nginx:1.25-alpine

RUN rm -rf /etc/share/nginx/html

COPY --from=build --chmod=755 /src/build /etc/share/nginx/html
ADD .docker/nginx/app.conf /etc/nginx/conf.d/app.conf

EXPOSE 8080