version: "3.8"
services:
    proxy:
        image: traefik:v2.10
        ports:
            - "80:80"
            - "443:443"
        networks:
            - services
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - .docker/traefik/traefik.yml:/traefik.yml:ro
            - .docker/certs:/certs
            - .docker/traefik/configurations:/configurations
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=services"
            - "traefik.http.routers.traefik-secure.entrypoints=websecure"
            - "traefik.http.routers.traefik-secure.rule=Host(`traefik.localhost`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
            - "traefik.http.routers.traefik-secure.service=api@internal"
    api:
        build:
            dockerfile: .docker/Dockerfile-api
            context: .
        restart: unless-stopped
        environment:
            RR_DEBUG: "true"
            RR_XDEBUG: 1
            DATABASE_DSN: "mysql://eav:eav@database/eav_database"
        networks:
            - services
        depends_on:
            - cache
            - database
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./vendor:/app/vendor
            - ./.rr.yaml:/app/.rr.yaml
            - ./composer.json:/app/composer.json
            - ./composer.lock:/app/composer.lock
            - ./api:/app/api
            - ./eav:/app/eav
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=services"
            - "traefik.http.routers.api-secure.entrypoints=websecure"
            - "traefik.http.routers.api-secure.rule=Host(`localhost`) && PathPrefix(`/api`)"
            - "traefik.http.services.api-secure.loadbalancer.server.port=8080"
        logging:
            driver: "json-file"
            options:
                max-size: "30m"
                max-file: "3"
    app:
        build:
            dockerfile: .docker/Dockerfile-app
            context: .
        restart: unless-stopped
        networks:
            - services
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./node_modules:/src/node_modules
            - ./package.json:/src/package.json
            - ./package-lock.json:/src/package-lock.json
            - ./app:/src/app
            - ./.svelte-kit:/src/.svelte-kit
            - ./svelte.config.js:/src/svelte.config.js
            - ./tsconfig.json:/src/tsconfig.json
            - ./vite.config.ts:/src/vite.config.ts
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=services"
            - "traefik.http.routers.app-secure.entrypoints=websecure"
            - "traefik.http.routers.app-secure.rule=Host(`localhost`)"
            - "traefik.http.services.app-secure.loadbalancer.server.port=5173"
        logging:
            driver: "json-file"
            options:
                max-size: "30m"
                max-file: "3"
    database:
        image: mariadb:lts-jammy
        ports:
            - "3306:3306"
        restart: unless-stopped
        networks:
            - services
        volumes:
            - eav-data:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD: "root"
            MARIADB_USER: "eav"
            MARIADB_PASSWORD: "eav"
            MARIADB_DATABASE: "eav_database"
        logging:
            driver: "json-file"
            options:
                max-size: "30m"
                max-file: "3"
    cache:
        image: redis:6.2-alpine
        restart: unless-stopped
        networks:
            - services
        logging:
            driver: "json-file"
            options:
                max-size: "30m"
                max-file: "3"

networks:
    services:
        driver: bridge

volumes:
    eav-data: