tls:
    options:
        default:
            minVersion: "VersionTLS12"
    stores:
        default:
            defaultCertificate:
                certFile: /certs/cert.crt
                keyFile: /certs/cert.key